### ISSUE TITLE
Align small zeros to bottom of text

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/TheInterceptor#1166]
Currently how it looks ![image](https://github.com/user-attachments/assets/44a62dfb-8817-4c62-bcaf-66af4bae1ccf)

**Comment by MicahZoltu** [comment]
Adding a span to the `<p>` that contains the big and small text items resolves the issue.  The problem is that the 3 pieces of text are part of a bigger flexbox that is center aligned.  We want the text overall to be center aligned, but we want the text to bottom-align with each other so we can put the 3 text items in a `<span>` container (which is bottom aligned by default) that then sits inside the flex `<p>`.
