### ISSUE TITLE
edit address button expads the whole view and causes shaking

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#128]
![image](https://user-images.githubusercontent.com/13102010/214780727-fc45adee-7ce7-4157-9ea9-8d58f447cc84.png)

**Comment by MicahZoltu** [comment]
If it is the shaking I'm thinking of, it is probably because you are adding a border on hover and using browser default [box sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).  Easy fix (to make it apply everywhere):
```css
* {
	box-sizing: border-box;
}
```
The reason browsers default to `content-box` is for legacy compatibility.  I think at this point everyone agrees that `border-box` is the right default for any *new* website.
