### ISSUE TITLE
fix error reporting on add new addr

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#154]
![image](https://user-images.githubusercontent.com/13102010/216776220-ed0bcd56-d69d-4b18-90ba-e2c5a47b8b05.png)

**Comment by MicahZoltu** [comment]
How do you guess at the "did you mean"?  Is that just the *correctly* check-summed address that is proposed?

I wonder how safe it is to ask a "did you mean x" here?  The purpose of the checksum is to ensure the user is copying an address, and if the checksum is wrong it means they may not be copying an address.  If we just "fix it for them", then it defeats the purpose.

**Comment by KillariDev** [comment]
yeah, I do the correctly check summed address with that guess (I do tolower and then checksum it correctly). We don't just fix it, we propose a solution, but if the user just blindly copies it always, then it defeats the purpose. I am not sure if its better that we don't show it.

**Comment by MicahZoltu** [comment]
I see 3 possible scenarios:
A. The user copies an address from someplace that has checksummed addresses.
B. The user copies an address from someplace that doesn't checksum, (all uppercase or all lowercase).
C. The user copies not-an-address from somewhere that has mixed case
D. The user tries to manually type an address and they typo it, then we should error and tell them to double-check the source.

(C) and (D) are the only ones of interest for the "did you mean", and in both scenarios think we should *not* offer a suggestion but instead tell them to verify that they are copying an address and double check all of the characters including casing.

Offering a "helpful suggestion" in the case of (D) is probably the worst thing we can do, as the checksum likely failed because they have a typo, not because the checksum was wrong.
