### ISSUE TITLE
Brave - Uncaught TypeError

### ISSUE THREAD

**Issue by randomishwalk** [DarkFlorist/TheInterceptor#16]
Brave version: [Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)](https://brave.com/latest/)

> Uncaught TypeError: Failed to resolve module specifier "webextension-polyfill". Relative references must start with either "/", "./", or "../".

![image](https://user-images.githubusercontent.com/94845277/205971521-a7777c80-beb7-4862-8934-40fc5be96ff2.png)

**Comment by randomishwalk** [comment]
Brave version: [Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)](https://brave.com/latest/)

> Uncaught TypeError: Failed to resolve module specifier "preact". Relative references must start with either "/", "./", or "../".

![image](https://user-images.githubusercontent.com/94845277/205972359-24c684d1-8e60-4f45-8ca9-da75b646b448.png)

**Comment by MicahZoltu** [comment]
See the line in the log immediately after that line.  😀  It is an "expected" error because we are using a polyfill for a feature that no browser supports yet (named imports), so it hacks around it which results in an error along the way.

**Comment by MicahZoltu** [comment]
From the console log of `background.html`:
```
Uncaught TypeError: Failed to resolve module specifier "webextension-polyfill". Relative references must start with either "/", "./", or "../".
es-module-shims.wasm.js:34 ^^ Module TypeError above is polyfilled and can be ignored ^^
```
The console for each of the other "pages" (popup and inpage) should have the same log line after the error.  Brave's error reporting only shows the error, but not surrounding context which is why we only see this error.

This error will go away once Brave implements import maps, so I'm going to close this as "won't fix".
